In [1]:
import numpy as np

In [2]:
a = np.arange(5.)

In [3]:
a

array([0., 1., 2., 3., 4.])

In [4]:
a.sum()

10.0

In [5]:
a.mean()

2.0

In [6]:
a.max()

4.0

In [7]:
a.min()

0.0

In [10]:
b = np.arange(9.).reshape(3, 3)

In [11]:
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [12]:
b.sum()

36.0

In [13]:
b.sum(axis=0)

array([ 9., 12., 15.])

In [14]:
b.sum(axis=1)

array([ 3., 12., 21.])

# ブロードキャスト

ブロードキャストされるexp, log, sqrtなどはユニバーサル関数と呼ばれる
ブロードキャストは関数だけでなく演算子にも使える

In [15]:
a = np.arange(3., 8.)

In [16]:
a

array([3., 4., 5., 6., 7.])

In [17]:
np.exp(a)

array([  20.08553692,   54.59815003,  148.4131591 ,  403.42879349,
       1096.63315843])

In [18]:
np.log(a)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015])

In [19]:
np.sqrt(a)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131])

In [20]:
b = np.arange(9.).reshape(3, 3)

In [21]:
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [22]:
np.exp(b)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [23]:
a = np.arange(5)

In [24]:
a

array([0, 1, 2, 3, 4])

In [25]:
a + 3

array([3, 4, 5, 6, 7])

In [26]:
a * 3

array([ 0,  3,  6,  9, 12])

In [27]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [28]:
a >= 2

array([False, False,  True,  True,  True])

In [40]:
a != 3

array([ True,  True,  True, False,  True])

In [54]:
b = np.arange(9)

In [56]:
b.resize((3, 3))

In [58]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
b > 3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [60]:
a = np.array([10, 20, 30, 40])

In [61]:
b = np.array([False, True, True, False])

In [62]:
a[b]

array([20, 30])

In [64]:
c = np.array([[3, 4, 5], [6, 7, 8]])

In [65]:
c

array([[3, 4, 5],
       [6, 7, 8]])

In [66]:
d = np.array([[False, False, True], [False, True, True]])

In [67]:
c[d]

array([5, 7, 8])

In [68]:
a = np.arange(10)

In [69]:
a[a > 5]

array([6, 7, 8, 9])

In [70]:
a[(a >= 3) & (a < 6)]

array([3, 4, 5])

In [71]:
a[(a < 2) | (a >7)]

array([0, 1, 8, 9])

In [72]:
a[a % 3 != 0]

array([1, 2, 4, 5, 7, 8])

In [73]:
u = np.arange(4)

In [74]:
v = np.arange(3, 7)

In [75]:
u

array([0, 1, 2, 3])

In [76]:
v

array([3, 4, 5, 6])

In [77]:
u + v 

array([3, 5, 7, 9])

In [78]:
u - v

array([-3, -3, -3, -3])

In [79]:
u * v

array([ 0,  4, 10, 18])

In [80]:
np.dot(u, v)

32

In [81]:
(u * v).sum()

32

In [82]:
a = np.arange(9.).reshape(3, 3)

In [83]:
b = np.arange(4., 13.).reshape(3, 3)

In [84]:
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [85]:
b

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [86]:
a + b

array([[ 4.,  6.,  8.],
       [10., 12., 14.],
       [16., 18., 20.]])

In [87]:
a -b

array([[-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.]])

In [88]:
a * b

array([[ 0.,  5., 12.],
       [21., 32., 45.],
       [60., 77., 96.]])

In [89]:
a / b

array([[0.        , 0.2       , 0.33333333],
       [0.42857143, 0.5       , 0.55555556],
       [0.6       , 0.63636364, 0.66666667]])

In [90]:
np.dot(a, b)

array([[ 27.,  30.,  33.],
       [ 90., 102., 114.],
       [153., 174., 195.]])

In [91]:
a.dot(b)

array([[ 27.,  30.,  33.],
       [ 90., 102., 114.],
       [153., 174., 195.]])

In [92]:
a@b

array([[ 27.,  30.,  33.],
       [ 90., 102., 114.],
       [153., 174., 195.]])

In [93]:
a = np.arange(9.).reshape(3, 3)

In [108]:
v = np.arange(1., 4.)

In [109]:
v.shape

(3,)

In [95]:
a 

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [96]:
v

array([1., 2., 3.])

In [97]:
np.dot(a, v)

array([ 8., 26., 44.])

In [98]:
np.dot(v, a)

array([24., 30., 36.])

In [101]:
u = v.reshape(-1, 1)

In [110]:
u

array([[1.],
       [2.],
       [3.]])

In [111]:
u.shape

(3, 1)

In [100]:
np.dot(a, u)

array([[ 8.],
       [26.],
       [44.]])

In [103]:
np.dot(u, a)

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [105]:
w = v.reshape(1, -1)

In [112]:
w

array([[1., 2., 3.]])

In [113]:
w.shape

(1, 3)

In [107]:
np.dot(w, a)

array([[24., 30., 36.]])

In [114]:
a = np.arange(12.).reshape(4, 3)

In [115]:
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [116]:
b = np.arange(3.).reshape(1, 3)

In [117]:
c = np.arange(4.).reshape(4, 1)

In [118]:
b

array([[0., 1., 2.]])

In [119]:
c

array([[0.],
       [1.],
       [2.],
       [3.]])

In [120]:
a + b

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.],
       [ 9., 11., 13.]])

In [121]:
a * c

array([[ 0.,  0.,  0.],
       [ 3.,  4.,  5.],
       [12., 14., 16.],
       [27., 30., 33.]])

In [122]:
b - c 

array([[ 0.,  1.,  2.],
       [-1.,  0.,  1.],
       [-2., -1.,  0.],
       [-3., -2., -1.]])

In [123]:
s = a + b