In [3]:
import numpy as np

In [4]:
np.exp(2)

7.38905609893065

In [5]:
np.log(np.e)

1.0

In [6]:
np.sin(np.pi)

1.2246467991473532e-16

In [7]:
np.sqrt(3)

1.7320508075688772

In [8]:
a = np.array([2, 3, 5, 7, 8])

In [9]:
a[0]

2

In [10]:
a[1:3]

array([3, 5])

In [11]:
a[2:-1]

array([5, 7])

In [13]:
b = np.arange(5)

In [14]:
b

array([0, 1, 2, 3, 4])

In [15]:
c = np.arange(1, 3, 0.2)

In [16]:
c

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [18]:
a.dtype

dtype('int64')

In [19]:
c.dtype

dtype('float64')

In [20]:
d = np.array([1, 2, 3], dtype=np.float64)

In [21]:
d

array([1., 2., 3.])

In [22]:
d.dtype

dtype('float64')

In [23]:
e = np.arange(5.)

In [24]:
e

array([0., 1., 2., 3., 4.])

In [25]:
e.dtype

dtype('float64')

In [27]:
a = np.array([[2, 3, 4], [5, 6, 7]], dtype=np.float64)

In [28]:
a

array([[2., 3., 4.],
       [5., 6., 7.]])

In [29]:
a[0, 1]

3.0

In [30]:
a[:, 1]

array([3., 6.])

In [31]:
a[1, :]

array([5., 6., 7.])

In [32]:
a[0, 2:]

array([4.])

In [33]:
a[0, :2]

array([2., 3.])

In [34]:
a = np.arange(15.).reshape(3, 5)

In [35]:
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [36]:
a.shape

(3, 5)

In [37]:
a.ndim

2

In [38]:
a.size

15

In [39]:
b = np.arange(4.)

In [40]:
b.shape

(4,)

In [41]:
b.ndim

1

In [42]:
b.size

4

In [43]:
a = np.arange(16.)

In [44]:
c = a.reshape(4, -1)

In [45]:
c

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [46]:
c.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [47]:
c.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [48]:
b = np.arange(4.)

In [49]:
b.reshape(-1, 1)

array([[0.],
       [1.],
       [2.],
       [3.]])

In [51]:
b[:, np.newaxis]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [52]:
b[:, None]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [53]:
b.reshape(1, -1)

array([[0., 1., 2., 3.]])

In [54]:
b[np.newaxis, :]

array([[0., 1., 2., 3.]])

In [55]:
a = np.zeros((3, 4))

In [56]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
b = np.ones((2, 2))

In [58]:
b

array([[1., 1.],
       [1., 1.]])

In [59]:
c = np.empty((2, 5))

In [60]:
c

array([[1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8]])

In [61]:
d = np.linspace(0, 1, 10)

In [62]:
d

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [65]:
a = np.arange(6).reshape(2, -1)

In [66]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
b = np.arange(6, 12).reshape(2, -1)

In [77]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
np.r_[a, b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
np.c_[a, b]

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [75]:
c = np.arange(3)

In [79]:
d = np.arange(3, 6)

In [80]:
np.r_[c, d]

array([0, 1, 2, 3, 4, 5])

In [81]:
np.c_[c, d]

array([[0, 3],
       [1, 4],
       [2, 5]])

In [82]:
np.r_[a, c]

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [84]:
np.r_[a, c.reshape(1, -1)]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])