In [3]:
import numpy as np

In [4]:
a = np.array([[3, 1, 1], [1, 2, 1], [0, -1, 1]])

In [6]:
# この方法でも逆行列を求めることができるがより高速で数値的に安定な方法がある
np.linalg.inv(a)

array([[ 0.42857143, -0.28571429, -0.14285714],
       [-0.14285714,  0.42857143, -0.28571429],
       [-0.14285714,  0.42857143,  0.71428571]])

In [7]:
b = np.array([1, 2, 3])

In [9]:
# 一次方程式を解く方が高速かつ数値的安定
np.linalg.solve(a, b)

array([-0.57142857, -0.14285714,  2.85714286])

In [11]:
from scipy import linalg

In [13]:
# LU分解アルゴリズム
lu , p = linalg.lu_factor(a)

In [14]:
linalg.lu_solve((lu, p), b)

array([-0.57142857, -0.14285714,  2.85714286])