In [1]:
import numpy as np

In [3]:
np.random.rand()

0.02234464710205819

In [4]:
# 配列を返す
np.random.rand(3, 2)

array([[0.02933304, 0.69583482],
       [0.41987638, 0.61894909],
       [0.53571404, 0.17733838]])

In [5]:
np.random.rand(5)

array([0.35758407, 0.17351853, 0.75398771, 0.40587894, 0.42980973])

In [6]:
np.random.randint(4)

2

In [7]:
# 範囲内の乱数を返す
np.random.randint(10, 20)

11

In [8]:
np.random.randint(5, size=(3, 3))

array([[3, 0, 2],
       [2, 4, 3],
       [0, 1, 3]])

In [9]:
def throw_dice(n):
    return np.random.randint(1, 7, size=n).sum()

In [10]:
throw_dice(10)

37

In [11]:
throw_dice(10)

34

In [13]:
throw_dice(10)

39

In [14]:
np.random.seed(10)

In [15]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [16]:
np.random.seed(10)

In [17]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [18]:
np.random.seed(100)

In [19]:
np.random.rand(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [20]:
np.random.seed(100)

In [21]:
np.random.rand(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [22]:
def throw_dice2(n, random_seed=10):
    np.random.seed(random_seed)
    return np.random.randint(1, 7, size=n).sum()

In [23]:
throw_dice2(10)

34

In [24]:
throw_dice2(10)

34

In [25]:
throw_dice2(100)

328

In [26]:
throw_dice2(100)

328

In [27]:
class Dice():
    def __init__(self):
        np.random.seed(0)
        self.sum_=0
        
    def throw(self):
        self.sum_ += np.random.randint(1, 7)
        
    def get_sum(self):
        return self.sum_

In [ ]:
d1 = Dice()

for _ in range(10):
    d1.throw()
    
d1.get_sum()

In [31]:
d2 = Dice()

for _ in range(10):
    d2.throw()
    
d2.get_sum()

39

In [35]:
# seedはグローバルな状態を変化させるため異なる値になる
d3 = Dice()
d4 = Dice()
for _ in range(10):
    d3.throw()
    d4.throw()

In [36]:
d3.get_sum()

34

In [37]:
d4.get_sum()

33

In [38]:
# インスタンスごとに異なる乱数発生器を持たせる必要がある
rs = np.random.RandomState(10)
rs.rand()

0.771320643266746

In [39]:
rs.rand()

0.0207519493594015

In [52]:
# 再現性を持たせることができる
class Dice2():
    def __init__(self, random_seed=None):
        self.random_state_ = np.random.RandomState(random_seed)
        self.sum_=0
        
    def throw(self):
        self.sum_ += self.random_state_.randint(1, 7)
        
    def get_sum(self):
        return self.sum_

In [56]:
dd1 = Dice2(123)
dd2 = Dice2(123)
for _ in range(10):
    dd1.throw()
    dd2.throw()

In [57]:
dd1.get_sum()

34

In [58]:
dd2.get_sum()

34